### ISSUE TITLE
TeXLive 2018 errors on some infopakket tex

### ISSUE THREAD

**Issue by tomkooij** [HiSPARC/infopakket#50]
A recent build failed: https://travis-ci.org/HiSPARC/infopakket/builds/387703827

This builds on TeXLive 2015 and pdftex (sharelatex) without errors or warnings, but it fails.

I've created a travis build with verbose output: https://travis-ci.org/HiSPARC/infopakket/builds/387709971

Sadly, TeXLive 2018 will not run on CentOS 6 (glibc 2.14 required, 2.12 installed), it will not install on my laptop (literally takes hours) so I'm stuck debugging this on travis.

This is a reminder. I'll post a piece of the log later.

**Comment by davidfokkema** [comment]
Fixed in fd26597. Apparently, you can't have the same name for a figure and the main TeX file. So when it compiled event_histogram.tex and looked for Event_histogram.png somehow it really, really wanted to include event_histogram.pdf, which didn't exist yet. I renamed the figure and all is well. Much easier to fix locally, ;-)!
